name: "CUKTECH BLE Server"
version: "0.1.0"
slug: "cuktech_ble"
description: "CUKTECH 10 Ultra BLE server for Home Assistant"
arch:
  - amd64
startup: application
boot: auto
init: false
host_network: true
host_dbus: true
full_access: true
apparmor: false
webui: "http://[HOST]:8199/config.html"
